#!/usr/bin/env python3
"""Phase 1f - Build RE-analysis SFT data: teach HAWQ to write an expert
reverse-engineering ANALYSIS from x86-64 assembly alone (not raw decompilation,
which the existing `decompile` family already covers).

Gold analyses are generated by a FRONTIER model that is handed decompile-bench's
real ground-truth C alongside the asm, so it explains a known-correct answer and
cannot hallucinate a wrong decompilation. The stored training row's user turn
contains ASM ONLY (no C) so the trained model learns to analyze from assembly
without the answer key.

Frontier config is REQUIRED env - this must NOT default to a local LM Studio
endpoint (that would serve HAWQ itself, and training HAWQ on its own output
produces no lift):
    FRONTIER_BASE_URL   e.g. https://api.openai.com/v1
    FRONTIER_MODEL      a frontier model id (NOT hawq/razorstrike*)
    FRONTIER_API_KEY

Usage:
    N_TASKS=1500 EVAL_OUT=eval_re_tasks.jsonl PUSH=1 \
        FRONTIER_BASE_URL=... FRONTIER_MODEL=... FRONTIER_API_KEY=... \
        python3 scripts/build_re_analysis.py
"""

import os
import re
import json
import random
import urllib.request
from concurrent.futures import ThreadPoolExecutor
from datasets import load_dataset, DatasetDict, Dataset

# Constants (mirror scripts/build_re.py)
MAX_ASM = 6000       # x86-64 assembly length (chars)
MAX_CODE = 4000       # C/C++ source length (chars)
SEED = 42
N_TASKS = int(os.environ.get("N_TASKS", "1500"))
N_EVAL = int(os.environ.get("N_EVAL", "100"))
MAX_WORKERS = int(os.environ.get("MAX_WORKERS", "1"))
RETRIES = 2

RE_ANALYST_SYSTEM = (
    "You are an elite reverse engineer. Given x86-64 assembly from a compiled "
    "binary, produce a precise technical analysis: purpose, inputs/outputs, "
    "algorithm, and security-relevant behavior."
)

FRONTIER_SYSTEM = (
    "You are an elite reverse engineer. You will be shown x86-64 assembly for a "
    "function, together with the original C/C++ source it was compiled from. The "
    "source is provided ONLY so your analysis is factually correct - treat it as a "
    "private answer key. Write a precise technical analysis OF THE ASSEMBLY, exactly "
    "as an expert would who has ONLY the assembly in front of them and has never seen "
    "the source.\n"
    "Hard rules:\n"
    "- NEVER mention, quote, or allude to the source, the C/C++ code, an 'answer key', "
    "'ground truth', or the fact that you were given anything beyond the assembly. The "
    "reader has only the assembly.\n"
    "- Only assert a specific upstream function name, library, struct field name, or "
    "enum symbol when it is genuinely determinable from the assembly alone (embedded "
    "string literals, syscall numbers, well-known magic constants, or an unmistakable "
    "published algorithm). When an identification would depend on knowledge you could "
    "get only from the source, describe the behavior structurally instead, or hedge "
    "with 'appears to' / 'consistent with'.\n"
    "- Do NOT narrate a step-by-step 'let me verify... correct... correct' trace or any "
    "chain-of-thought. Output only the finished analysis.\n"
    "Structure the analysis as: (1) one-line purpose; (2) inputs/outputs and their "
    "types/registers; (3) the algorithm and control flow in prose; (4) security-relevant "
    "behavior (memory safety, bounds, integer overflow, crypto, parsing, syscalls). Be "
    "faithful to what the assembly actually does; never invent behavior."
)

FRONTIER_USER_TMPL = (
    "ASSEMBLY:\n```asm\n{asm}\n```\n"
    "KNOWN-CORRECT SOURCE (ground truth, for your reference only - do not echo "
    "it):\n```cpp\n{code}\n```\n"
    "Write the analysis now."
)


def _frontier_env():
    """Load and validate required FRONTIER_* env. Aborts on a local/HAWQ endpoint."""
    base_url = os.environ.get("FRONTIER_BASE_URL")
    model = os.environ.get("FRONTIER_MODEL")
    api_key = os.environ.get("FRONTIER_API_KEY")
    missing = [n for n, v in (("FRONTIER_BASE_URL", base_url),
                               ("FRONTIER_MODEL", model),
                               ("FRONTIER_API_KEY", api_key)) if not v]
    if missing:
        raise SystemExit(
            f"[frontier] required env missing: {', '.join(missing)}. "
            f"This builder must call a real frontier model, not the local HAWQ "
            f"server, to generate gold RE analyses.")

    if re.match(r"^(hawq|razorstrike)", model, re.IGNORECASE):
        raise SystemExit(
            f"[frontier] FRONTIER_MODEL={model!r} looks like a HAWQ/RazorStrike "
            f"model id, not a frontier model. Training HAWQ on its own output "
            f"produces no lift. Aborting.")

    local_hosts = ("127.0.0.1:1234", "localhost:1234", "generic:1234")
    if any(h in base_url for h in local_hosts):
        raise SystemExit(
            f"[frontier] FRONTIER_BASE_URL={base_url!r} points at a local LM "
            f"Studio endpoint (serves HAWQ itself). Aborting - supply a real "
            f"frontier endpoint (e.g. https://api.openai.com/v1).")

    return base_url.rstrip("/"), model, api_key


def _frontier_call(base_url, model, api_key, asm, code):
    """One frontier chat/completions call. Returns analysis text or None on failure."""
    url = f"{base_url}/chat/completions"
    body = {
        "model": model,
        # "none" is NOT a valid harmony reasoning_effort value for gpt-oss-class
        # models on Ollama Cloud - it's silently ignored and the model reasons
        # at full effort anyway, burning the whole token budget on a hidden
        # reasoning trace and leaving `content` truncated/empty (confirmed via
        # direct API probe: reasoning_effort="none" + max_tokens=1800 on a
        # near-max-size row -> finish_reason="length", content_len=0,
        # reasoning_len=6416). "low" empirically collapses the reasoning trace
        # to near-zero and lets `content` get the token budget.
        "reasoning_effort": os.environ.get("FRONTIER_REASONING_EFFORT", "low"),
        "messages": [
            {"role": "system", "content": FRONTIER_SYSTEM},
            {"role": "user", "content": FRONTIER_USER_TMPL.format(asm=asm, code=code)},
        ],
        "temperature": 0.3,
        "max_tokens": int(os.environ.get("FRONTIER_MAX_TOKENS", "2600")),
    }
    req = urllib.request.Request(
        url, data=json.dumps(body).encode(),
        headers={"Content-Type": "application/json", "Authorization": f"Bearer {api_key}"})
    for attempt in range(RETRIES + 1):
        try:
            with urllib.request.urlopen(req, timeout=90) as r:
                d = json.load(r)
            text = d["choices"][0]["message"]["content"].strip()
            if text:
                return text
        except Exception as e:
            if attempt == RETRIES:
                print(f"[frontier] call failed after {RETRIES + 1} attempts: "
                      f"{type(e).__name__}: {e}")
    return None


def format_train_row(asm, analysis):
    """Build the stored SFT row: user turn is ASM ONLY (no ground-truth C)."""
    messages = [
        {"role": "system", "content": RE_ANALYST_SYSTEM},
        {"role": "user",
         "content": f"Analyze this x86-64 function and explain what it does.\n\n```asm\n{asm}\n```"},
        {"role": "assistant", "content": analysis},
    ]
    return {
        "source": "LLM4Binary/decompile-bench",
        "family": "re_analysis",
        "messages": messages,
    }


def _load_kept_rows(need, skip=0):
    """Return `need` length-filtered rows sampled across the WHOLE corpus,
    after discarding the first `skip` qualifying rows. `skip` lets a second
    task family draw a provably disjoint slice of the same shuffled stream.

    Deduplicates by asm content across the WHOLE scan (not just the
    returned slice): decompile-bench has genuine corpus-level duplicate
    function bodies (common utility functions repeated across projects),
    confirmed empirically (~0.7% collision rate). Collapsing them into the
    stream itself - rather than filtering the returned slice after the
    fact - keeps the skip-based partition's disjointness guarantee exact:
    two disjoint slices of a globally-deduped stream can never collide,
    whereas two slices of a stream with duplicates could each independently
    encounter the same content."""
    print("Downloading decompile-bench...")
    local_dir = "/Volumes/Scratch/ml-workspace/decompile-bench"
    ds_raw = load_dataset("LLM4Binary/decompile-bench", split="train", cache_dir=local_dir)
    print(f"Raw decompile-bench: {len(ds_raw)} rows")
    ds_shuf = ds_raw.shuffle(seed=SEED)          # full-corpus permutation, not a head slice
    # Gated (default OFF): a live/resumable run must reproduce the EXACT
    # same stream on restart as its original launch, or RAW_CACHE entries
    # (keyed by asm) partially miss and the skip-based cross-family
    # partition silently shifts mid-run. Flip on explicitly for a fresh
    # run/rebuild once nothing is depending on stream stability.
    _dedup = os.environ.get("DEDUP_ASM", "0") == "1"
    kept, seen = [], 0
    seen_asms = set()
    for row in ds_shuf:
        asm, code = row["asm"], row["code"]
        if len(asm) <= MAX_ASM and len(code) <= MAX_CODE:
            if _dedup:
                if asm in seen_asms:
                    continue  # corpus-level duplicate function body - collapse, don't recount
                seen_asms.add(asm)
            seen += 1
            if seen <= skip:
                continue
            kept.append({"asm": asm, "code": code})
        if len(kept) >= need:
            break
    if len(kept) < need:
        raise RuntimeError(f"only found {len(kept)} kept rows, need {need} (skip={skip})")
    return kept


def build_re_analysis_dataset(n_tasks=N_TASKS, n_eval=N_EVAL, eval_out=None):
    base_url, model, api_key = _frontier_env()
    print(f"[frontier] using {model} @ {base_url}")

    kept = _load_kept_rows(n_tasks + n_eval)
    train_src = kept[:n_tasks]
    eval_src = kept[n_tasks:n_tasks + n_eval]
    print(f"[data] {len(train_src)} train rows, {len(eval_src)} eval rows (disjoint)")

    # Resumable, crash-safe generation cache: keyed by the ASM (the natural
    # unique key for a src row - same asm the eventual training row stores).
    # A multi-thousand-call run against a paid frontier API must not lose
    # already-paid-for work to a crash/timeout partway through, and must not
    # re-pay for rows a prior partial run already generated.
    raw_cache = os.environ.get("RAW_CACHE", "/tmp/hawq_re/raw_generations.jsonl")
    os.makedirs(os.path.dirname(raw_cache), exist_ok=True)
    cached = {}
    if os.path.exists(raw_cache):
        with open(raw_cache) as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                row = json.loads(line)
                cached[row["messages"][1]["content"]] = row
        print(f"[gen] resumed {len(cached)} already-generated rows from {raw_cache}")

    cache_lock = __import__("threading").Lock()
    cache_f = open(raw_cache, "a")

    def _user_turn(asm):
        return format_train_row(asm, "")["messages"][1]["content"]

    def gen_one(src_row):
        key = _user_turn(src_row["asm"])
        if key in cached:
            return cached[key]
        analysis = _frontier_call(base_url, model, api_key, src_row["asm"], src_row["code"])
        if not analysis:
            return None
        row = format_train_row(src_row["asm"], analysis)
        with cache_lock:
            cache_f.write(json.dumps(row) + "\n")
            cache_f.flush()
        return row

    train_rows = []
    if MAX_WORKERS > 1:
        with ThreadPoolExecutor(max_workers=MAX_WORKERS) as ex:
            for i, r in enumerate(ex.map(gen_one, train_src)):
                if r is not None:
                    train_rows.append(r)
                if (i + 1) % 50 == 0:
                    print(f"[gen] {i + 1}/{len(train_src)} processed, {len(train_rows)} kept")
    else:
        for i, src_row in enumerate(train_src):
            r = gen_one(src_row)
            if r is not None:
                train_rows.append(r)
            if (i + 1) % 50 == 0:
                print(f"[gen] {i + 1}/{len(train_src)} processed, {len(train_rows)} kept")
    cache_f.close()

    print(f"[gen] done: {len(train_rows)}/{len(train_src)} rows generated "
          f"({len(train_src) - len(train_rows)} skipped on frontier failure)")
    print(f"[gen] raw generations cached -> {raw_cache} (survives a guard failure below; "
          f"a re-run reads this back and only pays for what's still missing)")

    random.seed(SEED)
    random.shuffle(train_rows)
    n_val = max(1, int(len(train_rows) * 0.02))
    ds = DatasetDict({
        "train": Dataset.from_list(train_rows[n_val:]),
        "validation": Dataset.from_list(train_rows[:n_val]),
    })

    for split_name, split in ds.items():
        for i, row in enumerate(split):
            if len(row["messages"]) != 3 or row["messages"][-1]["role"] != "assistant":
                raise ValueError(f"{split_name}[{i}] malformed messages")
            if "```cpp" in row["messages"][1]["content"] or "KNOWN-CORRECT" in row["messages"][1]["content"]:
                raise ValueError(f"{split_name}[{i}] user turn leaks ground-truth C")

    import re as _re
    _SRC_REF = _re.compile(
        r"(?i)\b(source code|ground.?truth|known.?correct|answer key|"
        r"the c code|the c/c\+\+ (?:code|source)|provided source(?: code)?|"
        r"original source(?: code)?|given source(?: code)?|"
        r"as (?:given|provided|shown) in the (?:c|c\+\+|source)|"
        r"(?:was|am|were) (?:given|provided|shown) the (?:c|c\+\+|source) code)\b")
    _n = _hits = 0
    for split in ds.values():
        for row in split:
            _n += 1
            if _SRC_REF.search(row["messages"][-1]["content"]):
                _hits += 1
    _frac = _hits / max(_n, 1)
    print(f"[guard] gold source-reference rate: {_hits}/{_n} = {_frac:.3f}")
    assert _frac <= 0.05, (
        f"gold still references the source in {_frac:.1%} of rows (>5%); the "
        f"ASM-faithful prompt did not take. Do NOT train on this data.")

    if eval_out:
        with open(eval_out, "w") as f:
            for row in eval_src:
                f.write(json.dumps(row) + "\n")
        print(f"[eval] wrote {len(eval_src)} held-out tasks -> {eval_out}")

    return ds


if __name__ == "__main__":
    eval_out = os.environ.get("EVAL_OUT")
    ds = build_re_analysis_dataset(eval_out=eval_out)
    print(f"Train: {len(ds['train'])} | Validation: {len(ds['validation'])}")

    # Print a few sample rows for eyeball verification (N_TASKS=5 smoke run).
    for i, row in enumerate(ds["train"].select(range(min(3, len(ds["train"]))))):
        print(f"\n--- sample {i} ---")
        print("user:", row["messages"][1]["content"][:200], "...")
        print("assistant:", row["messages"][2]["content"][:300], "...")
    local_out = os.environ.get("LOCAL_OUT", "/tmp/hawq_re/hawq-re-analysis-dataset")
    ds.save_to_disk(local_out)
    print(f"[save] dataset saved locally -> {local_out} (durability checkpoint before push)")

    if os.environ.get("PUSH", "0") == "1":
        data_repo = os.environ.get("DATA_REPO", "lancejames221b/hawq-re-analysis")
        print(f"Pushing to HF: {data_repo}")
        try:
            ds.push_to_hub(data_repo, private=True)
            print("RE-analysis dataset pushed to HF")
        except Exception as e:
            print(f"[push] FAILED: {type(e).__name__}: {e}. "
                  f"Dataset is safe on local disk at {local_out} - retry with: "
                  f"python3 -c \"from datasets import load_from_disk; "
                  f"load_from_disk('{local_out}').push_to_hub('{data_repo}', private=True)\"")
            raise
