#!/usr/bin/env python3
"""Phase 1f - Build RE-analysis SFT data: teach HAWQ to write an expert
reverse-engineering ANALYSIS from x86-64 assembly alone (not raw decompilation,
which the existing `decompile` family already covers).

Gold analyses are generated by a FRONTIER model that is handed decompile-bench's
real ground-truth C alongside the asm, so it explains a known-correct answer and
cannot hallucinate a wrong decompilation. The stored training row's user turn
contains ASM ONLY (no C) so the trained model learns to analyze from assembly
without the answer key.

Frontier config is REQUIRED env - this must NOT default to a local LM Studio
endpoint (that would serve HAWQ itself, and training HAWQ on its own output
produces no lift):
    FRONTIER_BASE_URL   e.g. https://api.openai.com/v1
    FRONTIER_MODEL      a frontier model id (NOT hawq/razorstrike*)
    FRONTIER_API_KEY

Usage:
    N_TASKS=1500 EVAL_OUT=eval_re_tasks.jsonl PUSH=1 \
        FRONTIER_BASE_URL=... FRONTIER_MODEL=... FRONTIER_API_KEY=... \
        python3 scripts/build_re_analysis.py
"""

import os
import re
import json
import random
import urllib.request
from concurrent.futures import ThreadPoolExecutor
from datasets import load_dataset, DatasetDict, Dataset

# Constants (mirror scripts/build_re.py)
MAX_ASM = 6000       # x86-64 assembly length (chars)
MAX_CODE = 4000       # C/C++ source length (chars)
SEED = 42
N_TASKS = int(os.environ.get("N_TASKS", "1500"))
N_EVAL = 100
MAX_WORKERS = int(os.environ.get("MAX_WORKERS", "1"))
RETRIES = 2

RE_ANALYST_SYSTEM = (
    "You are an elite reverse engineer. Given x86-64 assembly from a compiled "
    "binary, produce a precise technical analysis: purpose, inputs/outputs, "
    "algorithm, and security-relevant behavior."
)

FRONTIER_SYSTEM = (
    "You are an elite reverse engineer and educator. You are given x86-64 "
    "assembly AND the known-correct C/C++ source it compiles from. Using the "
    "source as ground truth, write a precise technical ANALYSIS of the "
    "function: (1) one-line purpose, (2) inputs/outputs and types, (3) the "
    "algorithm/control-flow in prose, (4) any security-relevant behavior "
    "(memory safety, bounds, crypto, parsing, syscalls). Do NOT reproduce the "
    "C source verbatim; explain it. Be faithful to the provided source; never "
    "invent behavior not present in it."
)

FRONTIER_USER_TMPL = (
    "ASSEMBLY:\n```asm\n{asm}\n```\n"
    "KNOWN-CORRECT SOURCE (ground truth, for your reference only - do not echo "
    "it):\n```cpp\n{code}\n```\n"
    "Write the analysis now."
)


def _frontier_env():
    """Load and validate required FRONTIER_* env. Aborts on a local/HAWQ endpoint."""
    base_url = os.environ.get("FRONTIER_BASE_URL")
    model = os.environ.get("FRONTIER_MODEL")
    api_key = os.environ.get("FRONTIER_API_KEY")
    missing = [n for n, v in (("FRONTIER_BASE_URL", base_url),
                               ("FRONTIER_MODEL", model),
                               ("FRONTIER_API_KEY", api_key)) if not v]
    if missing:
        raise SystemExit(
            f"[frontier] required env missing: {', '.join(missing)}. "
            f"This builder must call a real frontier model, not the local HAWQ "
            f"server, to generate gold RE analyses.")

    if re.match(r"^(hawq|razorstrike)", model, re.IGNORECASE):
        raise SystemExit(
            f"[frontier] FRONTIER_MODEL={model!r} looks like a HAWQ/RazorStrike "
            f"model id, not a frontier model. Training HAWQ on its own output "
            f"produces no lift. Aborting.")

    local_hosts = ("127.0.0.1:1234", "localhost:1234", "generic:1234")
    if any(h in base_url for h in local_hosts):
        raise SystemExit(
            f"[frontier] FRONTIER_BASE_URL={base_url!r} points at a local LM "
            f"Studio endpoint (serves HAWQ itself). Aborting - supply a real "
            f"frontier endpoint (e.g. https://api.openai.com/v1).")

    return base_url.rstrip("/"), model, api_key


def _frontier_call(base_url, model, api_key, asm, code):
    """One frontier chat/completions call. Returns analysis text or None on failure."""
    url = f"{base_url}/chat/completions"
    body = {
        "model": model,
        "reasoning_effort": "none",  # Ollama Cloud reasoning models otherwise
                                      # burn the token budget on a hidden
                                      # reasoning trace and leave `content`
                                      # empty/truncated; this forces the
                                      # final analysis straight into content.
        "messages": [
            {"role": "system", "content": FRONTIER_SYSTEM},
            {"role": "user", "content": FRONTIER_USER_TMPL.format(asm=asm, code=code)},
        ],
        "temperature": 0.3,
        "max_tokens": 1800,
    }
    req = urllib.request.Request(
        url, data=json.dumps(body).encode(),
        headers={"Content-Type": "application/json", "Authorization": f"Bearer {api_key}"})
    for attempt in range(RETRIES + 1):
        try:
            with urllib.request.urlopen(req, timeout=90) as r:
                d = json.load(r)
            text = d["choices"][0]["message"]["content"].strip()
            if text:
                return text
        except Exception as e:
            if attempt == RETRIES:
                print(f"[frontier] call failed after {RETRIES + 1} attempts: "
                      f"{type(e).__name__}: {e}")
    return None


def format_train_row(asm, analysis):
    """Build the stored SFT row: user turn is ASM ONLY (no ground-truth C)."""
    messages = [
        {"role": "system", "content": RE_ANALYST_SYSTEM},
        {"role": "user",
         "content": f"Analyze this x86-64 function and explain what it does.\n\n```asm\n{asm}\n```"},
        {"role": "assistant", "content": analysis},
    ]
    return {
        "source": "LLM4Binary/decompile-bench",
        "family": "re_analysis",
        "messages": messages,
    }


def _load_kept_rows(need):
    """Download decompile-bench, filter by length, shuffle (SEED), return `need` kept rows."""
    print("Downloading decompile-bench...")
    local_dir = "/Volumes/Scratch/ml-workspace/decompile-bench"
    ds_raw = load_dataset("LLM4Binary/decompile-bench", split="train", cache_dir=local_dir)
    print(f"Raw decompile-bench: {len(ds_raw)} rows")

    kept = []
    for row in ds_raw:
        asm, code = row["asm"], row["code"]
        if len(asm) <= MAX_ASM and len(code) <= MAX_CODE:
            kept.append({"asm": asm, "code": code})
        if len(kept) >= need * 3:  # enough headroom before shuffle-slice
            break

    random.seed(SEED)
    random.shuffle(kept)
    if len(kept) < need:
        raise RuntimeError(f"only found {len(kept)} kept rows, need {need}")
    return kept


def build_re_analysis_dataset(n_tasks=N_TASKS, n_eval=N_EVAL, eval_out=None):
    base_url, model, api_key = _frontier_env()
    print(f"[frontier] using {model} @ {base_url}")

    kept = _load_kept_rows(n_tasks + n_eval)
    train_src = kept[:n_tasks]
    eval_src = kept[n_tasks:n_tasks + n_eval]
    print(f"[data] {len(train_src)} train rows, {len(eval_src)} eval rows (disjoint)")

    def gen_one(src_row):
        analysis = _frontier_call(base_url, model, api_key, src_row["asm"], src_row["code"])
        if not analysis:
            return None
        return format_train_row(src_row["asm"], analysis)

    train_rows = []
    if MAX_WORKERS > 1:
        with ThreadPoolExecutor(max_workers=MAX_WORKERS) as ex:
            for i, r in enumerate(ex.map(gen_one, train_src)):
                if r is not None:
                    train_rows.append(r)
                if (i + 1) % 50 == 0:
                    print(f"[gen] {i + 1}/{len(train_src)} processed, {len(train_rows)} kept")
    else:
        for i, src_row in enumerate(train_src):
            r = gen_one(src_row)
            if r is not None:
                train_rows.append(r)
            if (i + 1) % 50 == 0:
                print(f"[gen] {i + 1}/{len(train_src)} processed, {len(train_rows)} kept")

    print(f"[gen] done: {len(train_rows)}/{len(train_src)} rows generated "
          f"({len(train_src) - len(train_rows)} skipped on frontier failure)")

    random.seed(SEED)
    random.shuffle(train_rows)
    n_val = max(1, int(len(train_rows) * 0.02))
    ds = DatasetDict({
        "train": Dataset.from_list(train_rows[n_val:]),
        "validation": Dataset.from_list(train_rows[:n_val]),
    })

    for split_name, split in ds.items():
        for i, row in enumerate(split):
            if len(row["messages"]) != 3 or row["messages"][-1]["role"] != "assistant":
                raise ValueError(f"{split_name}[{i}] malformed messages")
            if "```cpp" in row["messages"][1]["content"] or "KNOWN-CORRECT" in row["messages"][1]["content"]:
                raise ValueError(f"{split_name}[{i}] user turn leaks ground-truth C")

    if eval_out:
        with open(eval_out, "w") as f:
            for row in eval_src:
                f.write(json.dumps(row) + "\n")
        print(f"[eval] wrote {len(eval_src)} held-out tasks -> {eval_out}")

    return ds


if __name__ == "__main__":
    eval_out = os.environ.get("EVAL_OUT")
    ds = build_re_analysis_dataset(eval_out=eval_out)
    print(f"Train: {len(ds['train'])} | Validation: {len(ds['validation'])}")

    # Print a few sample rows for eyeball verification (N_TASKS=5 smoke run).
    for i, row in enumerate(ds["train"].select(range(min(3, len(ds["train"]))))):
        print(f"\n--- sample {i} ---")
        print("user:", row["messages"][1]["content"][:200], "...")
        print("assistant:", row["messages"][2]["content"][:300], "...")
    local_out = os.environ.get("LOCAL_OUT", "/tmp/hawq_re/hawq-re-analysis-dataset")
    ds.save_to_disk(local_out)
    print(f"[save] dataset saved locally -> {local_out} (durability checkpoint before push)")

    if os.environ.get("PUSH", "0") == "1":
        data_repo = os.environ.get("DATA_REPO", "lancejames221b/hawq-re-analysis")
        print(f"Pushing to HF: {data_repo}")
        try:
            ds.push_to_hub(data_repo, private=True)
            print("RE-analysis dataset pushed to HF")
        except Exception as e:
            print(f"[push] FAILED: {type(e).__name__}: {e}. "
                  f"Dataset is safe on local disk at {local_out} - retry with: "
                  f"python3 -c \"from datasets import load_from_disk; "
                  f"load_from_disk('{local_out}').push_to_hub('{data_repo}', private=True)\"")
            raise
